Migrate missing v4 target keys to v4
adobe/aepsdk-core-android pull request #334
Opened 2023-01-18 22:29 UTC by spoorthipujariadobe

## Description

- Migrated missing keys sessionId and edgeHost from v4 to v5
- Fixed related tests

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-01-19 20:49 UTC, swarna04 requested changes

2023-01-19 20:49 UTC, swarna04 commented on code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/AndroidV4ToV5MigrationTests.java
> +        assertTrue(v4DataStore.contains(V4.Target.THIRD_PARTY_ID));
Fix assertion here for Edge host 
```
assertTrue(v4DataStore.contains(V4.Target.EDGE_HOST));
```

2023-01-19 20:49 UTC, swarna04 commented on code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/AndroidV4ToV5MigrationTests.java
> +        assertTrue(v4DataStore.contains(V4.Target.THIRD_PARTY_ID));
Assert v5 Target data store doesn't contain session ID and edge host too when privacy is opted out L561-562

2023-01-20 21:53 UTC, swarna04 commented on code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/AndroidV4ToV5MigrationTests.java
> +        assertTrue(v4DataStore.contains(V4.Target.THIRD_PARTY_ID));
I've pushed the feedback updates to this pr @praveek

2023-01-20 23:00 UTC, praveek approved these changes

2023-01-20 23:01 UTC, merged